### ISSUE TITLE
Add hotfix command

### ISSUE THREAD

**Issue by noisecapella** [mitodl/release-script#201] opened 2019-08-07 16:39 UTC
Given a commit hash doof should start a release containing only the cherry-picked hotfix commit. Release notes and tags should be applied as usual.

I think the tricky thing here is:
 - what if the cherry pick onto release candidate fails?
 - what if the merge back into master fails afterwards?

Probably the best thing to do is give up and provide a helpful error message

**Comment by pdpinch** [comment] 2019-08-20 12:30
@mbertrand can you review this and weigh in on the questions?

**Comment by mbertrand** [comment] 2019-08-20 13:08
When creating a hotfix release manually, there was a problem encountered finishing the release.  The manual process was as follows:
- Manually create a release-candidate PR that includes the hotfix
- Copy/paste the description from an earlier RC PR and update the issue description/commit
- `doof wait for checkboxes`
- when the checkboxes were checked, I clicked 'Finish release' but the command failed.  I don't remember the exact log message unfortunately.  
- Manually tagged the RC with the version
- Manually merged to release
- Manually merged to master

**Comment by annagav** [comment] 2019-08-20 20:06
@mbertrand, I think part of the issue is also deciding what to do with the current open release PR. Should we just close it, and start the relesse over again, when the hotfix is out?

**Comment by mbertrand** [comment] 2019-08-20 20:07
Yes, that sounds good to me.

**Closed** 2019-09-04 18:14 UTC
